### ISSUE TITLE
Texts are not centered

### ISSUE THREAD

**Issue by Rishikesh-kumar-7258** [Rishikesh-kumar-7258/Block_breaker#2]
Texts are not centered and good looking.
Game specific font is needed.

**Comment by kbhavre** [comment]
I will try to work on this issue , Please guide me if any problem occurs

**Comment by Rishikesh-kumar-7258** [comment]
Ook work on this issue..
As you might have noticed you need to have understanding of pygame, more specially fonts. since you will be working on text centering problem. 
You have to make the texts aligned and centered.
After making the changes make a pull request.

**Comment by Rishikesh-kumar-7258** [comment]
Issue resolved
font = pygame.font.SysFont("Roboto", 55)
text = font.render(t, True, color, BLACK)
textRect = text.get_rect()
textRect.x = x
textRect.y = y
SCREEN.blit(text, (textRect[0] - textRect[2] / 2, textRect[1] - textRect[3] / 2))
